### ISSUE TITLE
Gracefully fail when there is no kerning

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/kernalytics-rf-ext#7]
Currently, there is just a traceback:
```
Traceback (most recent call last):
  File "kernGraph.py", line 633, in <module>
  File "kernGraph.py", line 181, in __init__
IndexError: list index out of range
Traceback (most recent call last):
  File "kernGraph.py", line 633, in <module>
  File "kernGraph.py", line 181, in __init__
IndexError: list index out of range

```

**Comment by frankrolf** [comment]
Fixed in https://github.com/adobe-type-tools/kernalytics-rf-ext/commit/09d248875f9513ca5dc0bc5ced1a26b87a55fd77
